### PR TITLE
errors: expose GoogleError

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Change-Id: I2a0e780640cde8ffa9b10815f5f15674dabea449

Exposing GoogleError to pub. Impl from GoogleErrorResponse now returns GoogleError instead of Other. Added PartialEq derivation on Reason.

Change is required due to 

```rust
        Err(e) => match e {
            CloudStorageError::Google(google_error_response) => {
                if google_error_response.errors_has_reason(&GoogleErrorReason::Conflict) {
                    Ok(Bucket::read(&name).await?)
                } else {
                    Err(google_error_response.into())
                }
            }
            _ => Err(e.into()),
        },

```

### CODE REVIEW

**Comment by ThouCheese** [comment]
Will test this tonight and if it works I will merge it. Looks good, thanks!

**Comment by ThouCheese** [comment]
Hi @ernestas-poskus, so one day turned into four because I wanted to setup CI like you said. I got it working on the master branch, so can you maybe merge master back into this branch to see what the CI does?

**Comment by ernestas-poskus** [comment]
> so can you maybe merge master back into this branch to see what the CI does?

done :+1:

**Comment by ernestas-poskus** [comment]
```
test resources::object_access_control::tests::update ... FAILED

failures:

---- resources::bucket::tests::create stdout ----
thread 'main' panicked at 'serivce account file not valid: Error("EOF while parsing a value", line: 2, column: 0)', src/resources/service_account.rs:36:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ThouCheese** [comment]
:/ Thats not supposed to happen

**Comment by ThouCheese** [comment]
So apparently secrets are only accessible for PR's from forks:
```
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```
This makes sense of course, but I don't know how we can get meaningful CI on PR's with this restriction. For now I have created a branch named `ernestas`. If you change the PR to merge into that branch, I will accept it and the CI will run.

**Pull request merged**
