### PR TITLE
Add size method to download stream

### LINKED ISSUE #36: Return `content-length` header with download stream
`download_streamed` would ideally return the `content-length` header (or be a stream with an accurate `size_hint()`) to obviate an unnecessary extra request to fetch the object `size`.

### PR DESCRIPTION
**Pull request by nhynes**
resolves #36

### CODE REVIEW

**Comment by ThouCheese** [comment]
So this way `size_hint` of the iterator is not used, but I think that there is no we can make use of that. Now if the user wants to read the file to a Vec the flow would be:

```rust
let download = object.download_streamed().await?;
let mut data = if let Some(size) = download.size() {
    Vec::with_capacity(size)
} else {
    Vec::new()
};
for part in download.next().await? {
    data.extend(part);
}
```

This is not super convenient, and it requires that the users manually remembers to allocate the vector with the correct size. Can we come up with an API that is less error-prone?

**Comment by ThouCheese** [comment]
If we want to use a `Stream` with a `size_hint`, I think it is required to flatten the `Stream<Item=Vec<u8>>` to a `Stream<Item=u8>`, but I'm not sure what the performance implications of this are.

**Comment by nhynes** [comment]
You can do it, but to get the semantics to work out, you end up with this abomination
```rust
impl From<reqwest::Response> for Download {
    fn from(res: reqwest::Response) -> Self {
        use futures::{StreamExt, TryStreamExt};
        Self {
            size: res.content_length(),
            bytes: res
                .bytes_stream()
                .map(|chunk| match chunk {
                    Ok(chunk) => futures::stream::iter(chunk.into_iter().map(Ok)).boxed(),
                    Err(err) => futures::stream::once(async { Err(err.into()) }).boxed(),
                })
                .flatten()
                .boxed(),
        }
    }
}

impl Stream for Download {
    type Item = crate::Result<u8>;

    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut futures::task::Context,
    ) -> futures::task::Poll<Option<Self::Item>> {
        Stream::poll_next(self.bytes.as_mut(), cx)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        (
            0,
            self.size
                .and_then(|s| std::convert::TryInto::try_into(s).ok()),
        )
    }
}
```
The single-itemness seems wrong, but I trust rustc to vectorize it.

**Comment by ThouCheese** [comment]
>  I guess some benchmarking wouldn't hurt.

I'm afraid that the benchmarks would mostly just be benchmarking the internet speed :). 

> I think it is required to flatten the `Stream<Item=Vec<u8>>` to a `Stream<Item=u8>`

In reality, the stream is of the form `Stream<Item=crate::Result<Vec<u8>>>`. In order to produce the correct result, the resulting stream needs to be of the form `Stream<Item<crate::Result<u8>>`. In the ideal case I'd do this without copying, but an implementation might look look like:

```rust
let bytes = resp
    .bytes_stream()
    .flat_map(|chunk| {
        let iter = match chunk {
            Ok(chunk) => {
                let chunk: Vec<crate::Result<u8>> = chunk.into_iter().map(Ok).collect();
                chunk.into_iter()
            },
            Err(err) => vec![Err(err.into())].into_iter(),
        };
        futures::stream::iter(iter)
    });
```

The boxing can be avoided by using a custom stream implementor like so:

```rust
struct SizedByteStream<S> {
    bytes: S,
    size: Option<usize>,
}

impl<S> SizedByteStream<S> {
    fn new(bytes: S, size: Option<usize>) -> Self {
        Self {
            bytes,
            size,
        }
    }
}

impl<S: Stream<Item=crate::Result<u8>> + Unpin> Stream for SizedByteStream<S> {
    type Item = crate::Result<u8>;

    #[inline(always)]
    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Stream::poll_next(std::pin::Pin::new(&mut self.bytes), cx)
    }
    
    fn size_hint(&self) -> (usize, Option<usize>) {
        (self.size.unwrap_or(0), self.size)
    }
}
```

I have a working implementation on in the branch `feat/headers` if you have any feedback on avoiding the copies!

**Comment by nhynes** [comment]
I ran the straightforward boxing snippet from above  through `cargo asm` and found that rustc is actually able to devirtualize those `dyn`s when doing a release build (with LTO, of course). Note that the debug assembly has two derefs whereas the release one goes straight to the implementation of `poll_next` for the inner stream.

The tl;dr here is that I think the simple flattening implementation is actually fine for both performance and readability.

**Debug**
LLVM IR:

```ll
; <download_test::Download as futures_core::stream::Stream>::poll_next
; Function Attrs: uwtable
define void @"_ZN72_$LT$download_test..Download$u20$as$u20$futures_core..stream..Stream$GT$9poll_next17h28eda2818918cd26E"(%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"* noalias nocapture sret dereferenceable(24) %0, i64* align 8 dereferenceable(32) %1, i64** align 8 dereferenceable(8) %cx) unnamed_addr #0 !dbg !3629 {
start:
  %pointer.dbg.spill.i.i = alloca { {}*, [3 x i64]* }, align 8
  %2 = alloca { i8*, i64* }, align 8
  %self.dbg.spill.i = alloca { i8*, i64* }*, align 8
  %cx.dbg.spill = alloca i64**, align 8
  %self = alloca i64*, align 8
  store i64* %1, i64** %self, align 8
  call void @llvm.dbg.declare(metadata i64** %self, metadata !3633, metadata !DIExpression()), !dbg !3635
  store i64** %cx, i64*** %cx.dbg.spill, align 8
  call void @llvm.dbg.declare(metadata i64*** %cx.dbg.spill, metadata !3634, metadata !DIExpression()), !dbg !3636
; call <core::pin::Pin<P> as core::ops::deref::DerefMut>::deref_mut
  %_5 = call align 8 dereferenceable(32) %Download* @"_ZN70_$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..ops..deref..DerefMut$GT$9deref_mut17h9df49f865b5c3844E"(i64** align 8 dereferenceable(8) %self), !dbg !3637
  br label %bb1, !dbg !3637

bb1:                                              ; preds = %start
  %_4 = getelementptr inbounds %Download, %Download* %_5, i32 0, i32 3, !dbg !3637
  store { i8*, i64* }* %_4, { i8*, i64* }** %self.dbg.spill.i, align 8
  call void @llvm.dbg.declare(metadata { i8*, i64* }** %self.dbg.spill.i, metadata !3638, metadata !DIExpression()), !dbg !3649
  %_5.i = bitcast { i8*, i64* }* %_4 to { {}*, [3 x i64]* }*, !dbg !3651
; call <alloc::boxed::Box<T> as core::ops::deref::DerefMut>::deref_mut
  %3 = call { {}*, [3 x i64]* } @"_ZN73_$LT$alloc..boxed..Box$LT$T$GT$$u20$as$u20$core..ops..deref..DerefMut$GT$9deref_mut17hefec0eac6995e121E"({ {}*, [3 x i64]* }* align 8 dereferenceable(16) %_5.i), !dbg !3652
  %_4.0.i = extractvalue { {}*, [3 x i64]* } %3, 0, !dbg !3652
  %_4.1.i = extractvalue { {}*, [3 x i64]* } %3, 1, !dbg !3652
  %4 = getelementptr inbounds { {}*, [3 x i64]* }, { {}*, [3 x i64]* }* %pointer.dbg.spill.i.i, i32 0, i32 0
  store {}* %_4.0.i, {}** %4, align 8, !noalias !3653
  %5 = getelementptr inbounds { {}*, [3 x i64]* }, { {}*, [3 x i64]* }* %pointer.dbg.spill.i.i, i32 0, i32 1
  store [3 x i64]* %_4.1.i, [3 x i64]** %5, align 8, !noalias !3653
  call void @llvm.dbg.declare(metadata { {}*, [3 x i64]* }* %pointer.dbg.spill.i.i, metadata !3656, metadata !DIExpression()), !dbg !3661
  %6 = bitcast { i8*, i64* }* %2 to { {}*, [3 x i64]* }*, !dbg !3663
  %7 = getelementptr inbounds { {}*, [3 x i64]* }, { {}*, [3 x i64]* }* %6, i32 0, i32 0, !dbg !3663
  store {}* %_4.0.i, {}** %7, align 8, !dbg !3663, !noalias !3653
  %8 = getelementptr inbounds { {}*, [3 x i64]* }, { {}*, [3 x i64]* }* %6, i32 0, i32 1, !dbg !3663
  store [3 x i64]* %_4.1.i, [3 x i64]** %8, align 8, !dbg !3663, !noalias !3653
  %9 = getelementptr inbounds { i8*, i64* }, { i8*, i64* }* %2, i32 0, i32 0, !dbg !3664
  %10 = load i8*, i8** %9, align 8, !dbg !3664, !nonnull !4
  %11 = getelementptr inbounds { i8*, i64* }, { i8*, i64* }* %2, i32 0, i32 1, !dbg !3664
  %12 = load i64*, i64** %11, align 8, !dbg !3664, !nonnull !4
  %13 = insertvalue { i8*, i64* } undef, i8* %10, 0, !dbg !3664
  %14 = insertvalue { i8*, i64* } %13, i64* %12, 1, !dbg !3664
  %15 = insertvalue { i8*, i64* } undef, i8* %10, 0, !dbg !3665
  %16 = insertvalue { i8*, i64* } %15, i64* %12, 1, !dbg !3665
  %_3.0 = extractvalue { i8*, i64* } %16, 0, !dbg !3637
  %_3.1 = extractvalue { i8*, i64* } %16, 1, !dbg !3637
  br label %bb2, !dbg !3637

bb2:                                              ; preds = %bb1
  %17 = bitcast i8* %_3.0 to {}*, !dbg !3666
  %18 = bitcast i64* %_3.1 to [3 x i64]*, !dbg !3666
  %19 = bitcast [3 x i64]* %18 to void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)**, !dbg !3666
  %20 = getelementptr inbounds void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)*, void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)** %19, i64 3, !dbg !3666
  %21 = load void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)*, void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)** %20, align 8, !dbg !3666, !invariant.load !4, !nonnull !4
  call void %21(%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"* noalias nocapture sret dereferenceable(24) %0, {}* align 1 %17, i64** align 8 dereferenceable(8) %cx), !dbg !3666
  br label %bb3, !dbg !3666

bb3:                                              ; preds = %bb2
  ret void, !dbg !3667
}
```

ASM:

```asm
 push    rbp
 mov     rbp, rsp
 sub     rsp, 112
 mov     rax, rdi
 mov     qword, ptr, [rbp, -, 56], rsi
 mov     qword, ptr, [rbp, -, 48], rdx
 lea     rcx, [rbp, -, 56]
 mov     qword, ptr, [rbp, -, 64], rdi
 mov     rdi, rcx
 mov     qword, ptr, [rbp, -, 72], rdx
 mov     qword, ptr, [rbp, -, 80], rax
 call    <core::pin::Pin<P> as core::ops::deref::DerefMut>::deref_mut
 mov     qword, ptr, [rbp, -, 88], rax
 mov     rax, qword, ptr, [rbp, -, 88]
 add     rax, 16
 mov     qword, ptr, [rbp, -, 40], rax
 mov     rdi, rax
 call    <alloc::boxed::Box<T> as core::ops::deref::DerefMut>::deref_mut
 mov     qword, ptr, [rbp, -, 16], rax
 mov     qword, ptr, [rbp, -, 8], rdx
 mov     qword, ptr, [rbp, -, 32], rax
 mov     qword, ptr, [rbp, -, 24], rdx
 mov     rax, qword, ptr, [rbp, -, 32]
 mov     rcx, qword, ptr, [rbp, -, 24]
 mov     qword, ptr, [rbp, -, 96], rax
 mov     qword, ptr, [rbp, -, 104], rcx
 mov     rax, qword, ptr, [rbp, -, 96]
 mov     rdi, qword, ptr, [rbp, -, 64]
 mov     rsi, rax
 mov     rdx, qword, ptr, [rbp, -, 72]
 mov     rax, qword, ptr, [rbp, -, 104]
 call    qword, ptr, [rax, +, 24]
 mov     rax, qword, ptr, [rbp, -, 80]
 add     rsp, 112
 pop     rbp
 ret
```

**Release**

LLVM IR:

```ll
; <download_test::Download as futures_core::stream::Stream>::poll_next
; Function Attrs: nounwind
define void @"_ZN72_$LT$download_test..Download$u20$as$u20$futures_core..stream..Stream$GT$9poll_next17h536ce4d2ff439118E"(%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"* noalias nocapture sret dereferenceable(24) %0, i64* align 8 dereferenceable(32) %1, i64** align 8 dereferenceable(8) %cx) unnamed_addr #1 !dbg !3518 {
start:
  call void @llvm.dbg.value(metadata i64* %1, metadata !3528, metadata !DIExpression()), !dbg !3530
  call void @llvm.dbg.value(metadata i64** %cx, metadata !3529, metadata !DIExpression()), !dbg !3530
  call void @llvm.dbg.value(metadata i64** undef, metadata !3528, metadata !DIExpression(DW_OP_deref)), !dbg !3530
  %_4 = getelementptr inbounds i64, i64* %1, i64 2, !dbg !3531
  call void @llvm.dbg.value(metadata i64* %_4, metadata !3532, metadata !DIExpression()), !dbg !3547
  %2 = bitcast i64* %_4 to {}**, !dbg !3549
  %_5.idx.val2.i1 = load {}*, {}** %2, align 8, !dbg !3549
  %_5.idx1.i = getelementptr i64, i64* %1, i64 3, !dbg !3549
  %3 = bitcast i64* %_5.idx1.i to [3 x i64]**, !dbg !3549
  %_5.idx1.val.i = load [3 x i64]*, [3 x i64]** %3, align 8, !dbg !3549
  %4 = getelementptr inbounds [3 x i64], [3 x i64]* %_5.idx1.val.i, i64 0, i64 3, !dbg !3550
  %5 = bitcast i64* %4 to void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)**, !dbg !3550
  %6 = load void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)*, void (%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"*, {}*, i64**)** %5, align 8, !dbg !3550, !invariant.load !4, !nonnull !4
  tail call void %6(%"std::task::Poll<std::option::Option<std::result::Result<u8, std::boxed::Box<dyn std::error::Error>>>>"* noalias nocapture nonnull sret dereferenceable(24) %0, {}* align 1 %_5.idx.val2.i1, i64** nonnull align 8 dereferenceable(8) %cx) #12, !dbg !3550
  ret void, !dbg !3551
}
```

ASM:

```asm
 push    rbp
 mov     rbp, rsp
 push    rbx
 push    rax
 mov     rbx, rdi
 mov     rax, qword, ptr, [rsi, +, 16]
 mov     rcx, qword, ptr, [rsi, +, 24]
 mov     rsi, rax
 call    qword, ptr, [rcx, +, 24]
 mov     rax, rbx
 add     rsp, 8
 pop     rbx
 pop     rbp
 ret
```

**Comment by nhynes** [comment]
Okay, I messed with it a bit and also ended up with a `SizedByteStream` except with the flattening part using `TryStreamExt` instead of copying.

**Comment by ThouCheese** [comment]
Yes try_flatten is much better than copying! Thanks for this PR @nhynes!

**Pull request merged**
