### PR TITLE
Async api attempt 2

### PR DESCRIPTION
**Pull request by carols10cents**
Hi! I've got `Bucket`'s actions implemented [in the way we talked about](https://github.com/ThouCheese/cloud-storage-rs/pull/11#issuecomment-646630503); what do you think?

I also added a 1.5s sleep to the test bucket creation function; that seems to let me run all the tests without getting rate limited.

If you like this direction instead, the rest of the work that I know I need to do includes:

- Implement async actions on all the other resources as well
- Write actual documentation comments and update the code in the doc comments so that the doc tests pass
- Document the `sync` feature in the readme
- Reduce the duplication among the sync methods' implementations

### CODE REVIEW

**Comment by ThouCheese** [comment]
It looks fantastic, I think this is the right direction!

**Comment by carols10cents** [comment]
Great! I'm going to close the other PR then and I'll update this one once I've converted everything else.

**Comment by ernestas-poskus** [comment]
@carols10cents hey, do you have any timeline when async support will be finished?

**Comment by carols10cents** [comment]
@ernestas-poskus nope!

**Pull request merged**
